### ISSUE TITLE
Strange output when opening "other locations" in Nautilus

### ISSUE THREAD

**Issue by fbruetting** [bil-elmoussaoui/nautilus-git#10]
```
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/git.py", line 417, in get_widget
    if is_git(uri):
  File "/usr/share/nautilus-python/extensions/git.py", line 62, in is_git
    output = execute('git rev-parse --is-inside-work-tree', folder_path).lower()
  File "/usr/share/nautilus-python/extensions/git.py", line 80, in execute
    stderr=PIPE, cwd=working_dir)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: 'ocations:///'
```

**Comment by bilelmoussaoui** [comment]
I will fix that soon :)  Thanks for reporting

**Comment by bilelmoussaoui** [comment]
Fixed on master, i will push a new update right now !
