### ISSUE TITLE
Git information not displayed

### ISSUE THREAD

**Issue by vlktomas** [bil-elmoussaoui/nautilus-git#33]
Hi I just installed extension but nothing is shown in directories with git repository. I have Ubuntu 14.04 and Nautilus 3.10.1.

Shell trace:

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/git.py", line 531, in get_widget
   widget = NautilusLocation(git, self.window)
  File "/usr/share/nautilus-python/extensions/git.py", line 243, in __init__
    self._build_widgets()
  File "/usr/share/nautilus-python/extensions/git.py", line 273, in _build_widgets
    self._generate_popover(button)
  File "/usr/share/nautilus-python/extensions/git.py", line 314, in _generate_popover
    self._popover = Gtk.Popover()
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Popover'
```

**Comment by bilelmoussaoui** [comment]
Sorry but you need gtk 3.14+ in order to use the extension as we use a new widget only available in that version or newer

**Comment by vlktomas** [comment]
I thought so. Thank you for the quick reply.
