### ISSUE TITLE
Fedora 30 with copr

### ISSUE THREAD

**Issue by jonatasalves-hotmart** [bil-elmoussaoui/nautilus-git#49]
Hi,
When I run:
```
dnf copr enable -y heikoada/nautilus-git
dnf install nautilus-git
nautilus -q 
```
I get this error:
```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-git.py", line 39, in <module>
    from utils import is_git
  File "/usr/share/nautilus-git/src/utils.py", line 22, in <module>
    from urlparse import urlsplit
ModuleNotFoundError: No module named 'urlparse'
```
I tried to install the urllib / urlparse package in pip2/pip3 but I can't find them

**Comment by ceiphr** [comment]
I was able to fix this by building from source. I hope there will be a fix for the copr version at some point.
